### ISSUE TITLE
Feature Request: Mute/Unmute

### ISSUE THREAD

**Issue by ZeroPain** [davidcie/SetVolume#1]
Also Thank you for this just started using eventghost alot and this saved my butt when i kill windows HID so i could override generic hid. But it killed my volume control this allowed me to fix it

**Comment by davidcie** [comment]
Thanks for your suggestion. Should be easy enough, will look into it over the weekend.

**Comment by ZeroPain** [comment]
Awesome thank you

-------------------------------------------
Steven C Norder

**Comment by davidcie** [comment]
Took a while because I no longer actively use EventGhost and moved on to other projects..! But found a few spare minutes over the weekend to brush up my C++ and implement a few commands around sound muting in case anyone's still interested.
